### ISSUE TITLE
Can't create a project

### ISSUE THREAD

**Issue by jarrodek** [googlearchive/code-editor-app#1]
Hi,
I've brand new Chromebook Pixel from Google IO. On last session Joe Marini have shown us Code Editor Application for Chrome.
I have dev channel already on my Pixel, I downloaded the source code and I've loaded it as an application (in dev mode using "Load unpacked extension"). Maybe I did something wrong but I can't create new project. 
On app load I see "Uncaught TypeError: Cannot call method 'createReader' of undefined" in console (file_tree.js:16).
Then, when I try create a project I receive "Error: INVALID_MODIFICATION_ERR" (util.js:33).

I really like an idea to develop extensions/applications for Chrome inside Chrome. So I'll be waiting for update! :+1:

**Comment by gaurave** [comment]
Hi,

The code-editor does not still work on dev channel. It only works on the chromeOS canary channel. Will update when it is available.

Thanks,
- \- Gaurav

**Comment by sowbug** [comment]
Two things: the canary channel is the only one that contains the APIs needed for the code editor. Also, there's a flag you'll need to enable in order to make the API active. Just wait a bit (dev channel updates every week) and it'll start working.

**Comment by jarrodek** [comment]
Thanks for update. I'm waiting for api update :)

**Comment by FattusMannus** [comment]
Even in Version 29.0.1520.2 dev with syncfs enabled I still have problems - now having an issue on line 275 of spark.js:
this.fileTree.closeOpenedTabs();
Uncaught TypeError: Cannot call method 'closeOpenedTabs' of undefined

**Comment by gaurave** [comment]
@FattusMannus : Can you reproduce it, if yes can you please post the steps to reproduce it.

Thanks

**Comment by FattusMannus** [comment]
Launch app
Attempt to create project
Error occurs

Closing the app and restarting shows the name of the project you created but then creating a new file in the projects throws another error

**Comment by dinhvh** [comment]
Did you enable those flags in chrome://flags?
- Experimental Extension APIs
- Enable Syncfs directory operation

**Comment by FattusMannus** [comment]
Yes - both of those flags are enabled
