### ISSUE TITLE
Creating a Project

### ISSUE THREAD

**Issue by edagyeman-zz** [googlearchive/code-editor-app#3]
When I type the project name and click "create" nothing happens. Anybody else witnessing this? how to resolve?

**Comment by FattusMannus** [comment]
You need to be running the latest a dev build and enable syncfs and experimental Apis in chrome://flags 

Although that didn't fix the issue for me!

**Comment by SmokyBob** [comment]
Ok fixed it!

Need the following flags enabled:
chrome://flags/#enable-apps-devtool-app
chrome://flags/#enable-syncfs-directory-operation
chrome://flags/#extension-apis

**Comment by edagyeman-zz** [comment]
It worked! Thanks guys! @SmokyBob
