### ISSUE TITLE
background.js: AppWindow too dependent on screen resolution

### ISSUE THREAD

**Issue by kennystrawnmusic** [googlearchive/code-editor-app#9]
I decided to fork the project to attempt to fix this issue:

https://github.com/KennyStrawn177/resolution-independent-code-editor

Simply put, the AppWindow created by background.js to launch the code editor uses fixed window bounds instead of dynamically calculating them. The result? On devices with wider screens, like my Acer AC700-1099, the code editor pops up in the middle of the screen with ugly whitespace to the left and right while the code editor itself takes up the entire screen from top to bottom, and I'm sure on devices like the Pixel it would get even worse with the code editor looking more like Notepad than like a legitimate IDE. By using screen.availWidth, screen.availHeight, Math.floor, and arithmetic operations to adjust the resolution of the window accordingly (like I did in the hopefully temporarily forked project), we don't have that problem.

**Comment by SmokyBob** [comment]
Awesome!
I think you can issue a pullrequest with your commit and wait if the changes are merged into the maing branch.

**Comment by kennystrawnmusic** [comment]
Pull request should have been submitted as of yesterday...

**Comment by kennystrawnmusic** [comment]
Fix committed in the form of a pull request that supposedly created Issue 10... Relocating all discussion to that request.
